### ISSUE TITLE
Installation fails on WSL

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#107]
### What is the current behavior?

Doing `pip install octue@https://api.github.com/repos/octue/octue-sdk-python/tarball/feature/allow-cloud-storage-credentials-to-be-none` in WSL fails with a problem on installation of the blake3 dependency.

### What is the expected behavior?

The blake3 dependency should install without fail

### Your environment

  - Library Version: `https://api.github.com/repos/octue/octue-sdk-python/tarball/feature/allow-cloud-storage-credentials-to-be-none`
  - Platform Windows Subsystem for Linux

### Other information

- [x] stacktraces
```

Collecting blake3>=0.1.8 (from octue@ https://api.github.com/repos/octue/octue-sdk-python/tarball/feature/allow-cloud-storage-credentials-to-be-none->-r cloud_function/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/b8/db/ed0b905cc0ce5b50a38a6ab4a38c6d210c7c8882821d484511903d74bf4f/blake3-0.1.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-bbsafz1v/blake3/setup.py'
 
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bbsafz1v/blake3/

**Comment by thclark** [comment]
Open for a year with no further occurrences. Someone feel free to re-open this or a new issue if you find the same issue cropping up!
