### ISSUE TITLE
Octue fails to connect to a running service (power_loss)

### ISSUE THREAD

**Issue by nvn-nil** [octue/octue-sdk-python#178]
### What is the current behavior?

*If the current behavior is a bug, please provide any stack traces the steps reproduce and, if possible, a minimal demo of the problem.*

**[update]: I have the same scripts working in cmd and powershell directly in windows. The following happens when I do it in a wsl environment**

I cannot seem to ask a question to the power_loss service we have deployed.

I have set `GOOGLE_APPLICATION_CREDENTIALS=<github-test-actions-creds.json>`, originally added a new service account with the Pub/Sub admin and storage viewer roles but couldn't get it to work using those creds (same error).. So I thought maybe it's a delay in role propagation so I used creds from the Github test actions service account which is supposedly used to test deployment, etc.. I cannot get it working with this cred either

This is the code 
```
import json
import os
from octue.cloud.pub_sub.service import Service
from octue.resources import Datafile, Dataset, Manifest
from octue.resources.service_backends import GCPPubSubBackend

# Redacted
PROJECT_NAME = "<project name>"
BUCKET_NAME = "<bucket-name>"
SERVICE_ID = "octue.services.<id>"

time_series_dataset = Dataset(
    files=[
        Datafile.from_cloud(
            project_name=PROJECT_NAME,
            bucket_name=BUCKET_NAME,
            datafile_path="wind_time_series.txt",
            sequence=0,
            tags={"met_mast_id": "mst1", "timezone": "Asia/Tbilisi"},
            allow_overwrite=True,
        )
    ]
)

wind_map_dataset = Dataset(
    files=[
        Datafile.from_cloud(
            project_name=PROJECT_NAME,
            bucket_name=BUCKET_NAME,
            datafile_path="wind_map_2.asc",
            sequence=0,
            tags={"elevation": 105},
            labels={"wind-map"},
            allow_overwrite=True,
        ),
        Datafile.from_cloud(
            project_name=PROJECT_NAME,
            bucket_name=BUCKET_NAME,
            datafile_path="wind_map.asc",
            sequence=1,
            tags={"elevation": 115},
            labels={"wind-map"},
            allow_overwrite=True,
        ),
    ]
)

input_manifest = Manifest(
    datasets=[time_series_dataset, wind_map_dataset], keys={"time_series_dataset": 0, "wind_map_dataset": 1}
)

with open(r"configuration.json") as f:
    input_values = json.load(f)

backend = GCPPubSubBackend(
    project_name=PROJECT_NAME,
    credentials_environment_variable="GOOGLE_APPLICATION_CREDENTIALS"
)

asker = Service(backend)
subscription, question_uuid = asker.ask(service_id=SERVICE_ID, input_values=input_values, input_manifest=input_manifest)
answer = asker.wait_for_answer(subscription, timeout=1000)
```

The traceback on line `subscription, question_uuid = asker.ask(...)` is:
```
E0610 11:54:41.255694900   17203 ev_epollex_linux.cc:516]    Error shutting down fd 14. errno: 9
E0610 11:54:41.256008700   17203 ev_epollex_linux.cc:516]    Error shutting down fd 13. errno: 9
E0610 11:55:11.255341300   17202 ev_epollex_linux.cc:516]    Error shutting down fd 12. errno: 9
E0610 11:55:11.255393000   17202 ev_epollex_linux.cc:516]    Error shutting down fd 11. errno: 9
Traceback (most recent call last):
  File "/home/naveen/.cache/pypoetry/virtualenvs/windquest-zvezIlw4-py3.9/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 73, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/naveen/.cache/pypoetry/virtualenvs/windquest-zvezIlw4-py3.9/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/naveen/.cache/pypoetry/virtualenvs/windquest-zvezIlw4-py3.9/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1623306335.277942400","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5419,"referenced_errors":[{"created":"@1623306328.598307000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/naveen/.cache/pypoetry/virtualenvs/windquest-zvezIlw4-py3.9/lib/python3.9/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/home/naveen/.cache/pypoetry/virtualenvs/windquest-zvezIlw4-py3.9/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/naveen/source/windquest/test_power_loss.py", line 62, in <module>
    subscription, question_uuid = asker.ask(service_id=SERVICE_ID, input_values=input_values, input_manifest=input_manifest)
  File "/home/naveen/.cache/pypoetry/virtualenvs/windquest-zvezIlw4-py3.9/lib/python3.9/site-packages/octue/cloud/pub_sub/service.py", line 157, in ask
    if not question_topic.exists():
  File "/home/naveen/.cache/pypoetry/virtualenvs/windquest-zvezIlw4-py3.9/lib/python3.9/site-packages/octue/cloud/pub_sub/topic.py", line 46, in exists
    self.service.publisher.get_topic(topic=self.path)
  File "/home/naveen/.cache/pypoetry/virtualenvs/windquest-zvezIlw4-py3.9/lib/python3.9/site-packages/google/cloud/pubsub_v1/_gapic.py", line 40, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
  File "/home/naveen/.cache/pypoetry/virtualenvs/windquest-zvezIlw4-py3.9/lib/python3.9/site-packages/google/pubsub_v1/services/publisher/client.py", line 680, in get_topic
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/home/naveen/.cache/pypoetry/virtualenvs/windquest-zvezIlw4-py3.9/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/naveen/.cache/pypoetry/virtualenvs/windquest-zvezIlw4-py3.9/lib/python3.9/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/home/naveen/.cache/pypoetry/virtualenvs/windquest-zvezIlw4-py3.9/lib/python3.9/site-packages/google/api_core/retry.py", line 199, in retry_target
    six.raise_from(
  File "<string>", line 3, in raise_from
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling functools.partial(<function _wrap_unary_errors.<locals>.error_remapped_callable at 0x7fcdf219cb80>, topic: "projects/windquest/topics/octue.services.<id>"
, metadata=[('x-goog-request-params', 'topic=projects/windquest/topics/octue.services.<id>'), ('x-goog-api-client', 'gl-python/3.9.0 grpc/1.37.1 gax/1.26.3 gccl/2.4.2')]), last exception: 503 failed to connect to all addresses
```

If you want the actual file (with the correct names, etc), let me know 📦 

### What is the expected behavior?

I can ask a question and get an answer back

### Your environment

  - Library Version: `0.1.19`
  - Platform: windows WSL (ubuntu 20.04)

**Comment by thclark** [comment]
@nvn-nil Can you check GCR to make sure the service id is the one for the main service, rather than for (possibly) the test service please?

**Comment by nvn-nil** [comment]
Yeah I checked, the id is the one from the cloud run topic

**Comment by thclark** [comment]
We've verified this is a WSL problem. Works in powershell, not WSL so god knows what wsl have done…

**Comment by cortadocodes** [comment]
@nvn-nil is this still an issue?

**Comment by thclark** [comment]
Closing this, we've talked offline to @nvn-nil and haven't been able to track down the issue without significant further effort.

So, if anyone experiences this, please comment here and we'll re-open. Until then we assume a networking glitch.
