### ISSUE TITLE
CLI raises TypeError when running an app from IDE

### ISSUE THREAD

**Issue by time-trader** [octue/octue-sdk-python#20]
While running octue 0.1.3 app from IDE: 
```
python app.py run
```
Traceback (most recent call last):
  File "app.py", line 56, in <module>
    octue_cli(args)
  File "/home/batman/Software/anaconda3/envs/foam_2d_twine/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/batman/Software/anaconda3/envs/foam_2d_twine/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/batman/Software/anaconda3/envs/foam_2d_twine/lib/python3.8/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/home/batman/Software/anaconda3/envs/foam_2d_twine/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/batman/Software/anaconda3/envs/foam_2d_twine/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/batman/Software/anaconda3/envs/foam_2d_twine/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: octue_cli() missing 3 required positional arguments: 'data_dir', 'input_dir', and 'tmp_dir'

**Comment by time-trader** [comment]
Also, the analysis object is not instantiated in cli.py. 
`    ctx.ensure_object(dict)` 
`     ctx.obj["analysis"] = "VIBRATION"`
Which was just a placeholder?

**Comment by thclark** [comment]
@time-trader this should be fixed with the recent release, but we'll need to alter the calling function slightly so let me fiddle around and make a PR to show you how.

We're in a position to go through the subject of manifesting a lot more rigorously now - shall we set up a call? In the meantime you'll probably be able to get an idea from [this example app](https://github.com/octue/octue-sdk-python/tree/main/octue/templates/template-using-manifests)
