### ISSUE TITLE
KeyError 'app' on clearup

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#268]
### What is the current behavior?

We frequently get an occurrence of the following stack trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/octue/cloud/deployment/google/cloud_run.py", line 99, in answer_question
    service.answer(question)
  File "/usr/local/lib/python3.9/site-packages/octue/cloud/pub_sub/service.py", line 159, in answer
    raise error
  File "/usr/local/lib/python3.9/site-packages/octue/cloud/pub_sub/service.py", line 129, in answer
    analysis = self.run_function(
  File "/usr/local/lib/python3.9/site-packages/octue/runner.py", line 163, in run
    raise e
  File "/usr/local/lib/python3.9/site-packages/octue/runner.py", line 154, in run
    app.run(analysis)
  File "/usr/local/lib/python3.9/site-packages/octue/runner.py", line 271, in __exit__
    del sys.modules["app"]
KeyError: 'app'
```

The remainder of the code appears to have executed. I'm not sure whether `sys.modules['app']` being missing is a deeper underlying problem, or whether it's legitimate for it to be missing. In a multithreaded GUNICORN environment, is `sys.modules` shared (in which case we have a race condition between multiple calls to the service?

### What is the expected behavior?

No error ;)

### Your environment

Client environment - check with thclark

**Comment by thclark** [comment]
I'm going to close this as we haven't seen it in months. Not sure what fixed it though :(
