### ISSUE TITLE
Tests failing due to dependency

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#27]
Unit tests all pass when run in series, but [in travis, two tests fail.
](https://travis-ci.com/github/octue/octue-sdk-python/builds/202028046)
These are two tests of the run command of the CLI that pass by themselves, but not when run in serial with `test_fractal_configuration`. The two tests pass when run in serial with all other tests (i.e. when `test_fractal_configuration` is disabled. 

@cortadocodes thinks it's something to do with paths being leaked from the template setting and making their way into other tests using AppFrom.

Failure message, on Python 3.6.3
```
======================================================================
FAIL: test_run_command_can_be_added (tests.test_cli.RunnerTestCase)
Test that an arbitrary run command can be used in the run command of the CLI.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/octue/octue-sdk-python/tests/test_cli.py", line 41, in test_run_command_can_be_added
    assert CUSTOM_APP_RUN_MESSAGE in result.output
AssertionError
======================================================================
FAIL: test_run_command_works_with_data_dir (tests.test_cli.RunnerTestCase)
Test that the run command of the CLI works with the --data-dir option.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/octue/octue-sdk-python/tests/test_cli.py", line 55, in test_run_command_works_with_data_dir
    assert CUSTOM_APP_RUN_MESSAGE in result.output
AssertionError
----------------------------------------------------------------------
```

**Comment by thclark** [comment]
Interestingly I reproduce this behaviour for local tox tests on python 3.8.

But, for locally run tox tests on python 3.6.9 I get 4 errors, not 2, with the additional ones being:
```
======================================================================
FAIL: test_help (tests.test_cli.RunnerTestCase)
Ensure the help commands works in the CLI.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/thc29/Source/octue/octue-sdk-python/tests/test_cli.py", line 23, in test_help
    assert help_result.output.startswith('Usage')
AssertionError

======================================================================
FAIL: test_version (tests.test_cli.RunnerTestCase)
Ensure the version command works in the CLI.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/thc29/Source/octue/octue-sdk-python/tests/test_cli.py", line 18, in test_version
    assert 'version' in result.output
AssertionError

----------------------------------------------------------------------
```
This might be unrelated.

**Comment by thclark** [comment]
Ok. So what's happening:

1. `octue/templates/template-python-fractal/twine.json` has no `output_values`
2. `tests/data/twines/valid_schema_twine.json` has `output_values` with required property `width`
3. Invoking the full test harness (i.e. reproducing the error) causes `test_run_command_works_with_data_dir` to run, with
  - `TESTS_DIR=/Users/thc29/Source/octue/octue-sdk-python/tests`
  - `self.TWINE_FILE_PATH=/Users/thc29/Source/octue/octue-sdk-python/tests/data/twines/valid_schema_twine.json`
  - console output `Hello! The app is running!` **NB this is the fractal app output**
  - `result.output=`analysis-ebfbb81f-93d3-4a7c-b59b-d151cc691547 ERROR 2020-11-17 10:36:19,305 runner 13523 4518925760 'width'
4. The value of `width` is required by the fractal app (but the default in the twine is not used) so supplying configuration values without the `width` value will pass validation but cause a KeyError (after console logging "the app is running").
5. This is wrong because of course the incorrect app is being used... And misleading because of the weird way that jsonschema defaults are (not) dealt with.

Conclusion: I'm expecting an issue with `AppFrom` where the `app` module is not reloaded on repeat imports. Thus, if another app is loaded first, that'll be used for subsequent analyses.

We may not encounter this condition in real life, but if we do it'll be hella confusing for everybody. So, I propose we fix the issue rather than attempting to kludge a fix of the tests.
