### ISSUE TITLE
OSError not handled by the octue logger

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#334]
### What is the current behavior?

If an OSError is raised (like "no space left on device"), a further exception is raised because OSErrors are not convertable to JSON (see the textPayload in the following log entry).

<details>
<summary>
Example OSError
</summary>

```
OSError
Error in : [Errno 28] No space left on device
Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/octue/cloud/deployment/google/answer_pub_sub_question.py", line 68, in answer_question service.answer(question, answer_topic=answer_topic) File "/usr/local/lib/python3.8/site-packages/octue/cloud/pub_sub/service.py", line 158, in answer raise error File "/usr/local/lib/python3.8/site-packages/octue/cloud/pub_sub/service.py", line 128, in answer analysis = self.run_function( File "/usr/local/lib/python3.8/site-packages/octue/runner.py", line 171, in run raise e File "/usr/local/lib/python3.8/site-packages/octue/runner.py", line 158, in run app.app_module.App(analysis).run() File "/app/power_loss/app.py", line 178, in run answer = wake_service.ask( File "/usr/local/lib/python3.8/site-packages/octue/resources/child.py", line 47, in ask File "/usr/local/lib/python3.8/site-packages/octue/cloud/pub_sub/service.py", line 292, in wait_for_answer OSError: Error in : [Errno 28] No space left on device
```

</details>

```json
{
  "textPayload": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/octue/cloud/pub_sub/logging.py\", line 31, in emit\n  File \"/usr/local/lib/python3.8/json/__init__.py\", line 231, in dumps\nTypeError: Object of type OSError is not JSON serializable",
  "insertId": "61fe3046000a513d8b42438e",
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "revision_name": "power-loss-00145-xuc",
      "project_id": "windquest",
      "service_name": "power-loss",
      "configuration_name": "power-loss",
      "location": "europe-west1"
    }
  },
  "timestamp": "2022-02-05T08:07:34.676157Z",
  "severity": "ERROR",
  "labels": {
    "commit-sha": "1b6d4e1637e80095b0250b62eea860ec1a6e005d",
    "instanceId": "00bf4bf02d3e79599f05c42e139de470c9550a755f52d0656f3bd4eecc971edf6925f1239d15c2427ad2037c97604ec1f06ea9fefb0b1331638038886a08",
    "managed-by": "gcp-cloud-build-deploy-cloud-run",
    "gcb-trigger-id": "fb93af85-177c-4a48-871c-217d84c1b8b5",
    "gcb-build-id": "4cd4a643-a0c7-4f9c-881a-70eea74ea1e9"
  },
  "logName": "projects/windquest/logs/run.googleapis.com%2Fstderr",
  "receiveTimestamp": "2022-02-05T08:07:34.938563618Z"
}
```

### What is the expected behavior?

That class of exceptions should be handled by the logger.

**Comment by thclark** [comment]
@nvn-nil You might want to follow this, as it came up on power-loss. But it's just a consequence of the out of space errors, nothing core for you.
