### ISSUE TITLE
Credentials don't get set on cloud run services

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#374]
### What is the current behavior?

On services deployed to cloud run having upgraded form octue 0.10.x to octue 0.14.0, we now have a problem when attempting to download files from a manifest:

<details>
<summary>
See traceback
</summary>

```
insertId: "622f0738000303f7a6b64e49"
labels: {5}
logName: "projects/windquest/logs/run.googleapis.com%2Fstderr"
receiveTimestamp: "2022-03-14T09:13:28.404029922Z"
resource: {2}
severity: "ERROR"
textPayload: "Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/octue/cloud/deployment/google/answer_pub_sub_question.py", line 68, in answer_question
    service.answer(question, answer_topic=answer_topic)
  File "/usr/local/lib/python3.8/site-packages/octue/cloud/pub_sub/service.py", line 159, in answer
    raise error
  File "/usr/local/lib/python3.8/site-packages/octue/cloud/pub_sub/service.py", line 128, in answer
    analysis = self.run_function(
  File "/usr/local/lib/python3.8/site-packages/octue/runner.py", line 96, in run
    inputs = self.twine.validate(
  File "/usr/local/lib/python3.8/site-packages/twined/twine.py", line 398, in validate
    sources[strand_name] = method(strand_data, cls=klass, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/twined/twine.py", line 338, in validate_input_manifest
    return self._validate_manifest("input_manifest", source, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/twined/twine.py", line 201, in _validate_manifest
    return cls(**data)
  File "/usr/local/lib/python3.8/site-packages/octue/resources/manifest.py", line 39, in __init__
    self._instantiate_datasets(datasets or {})
  File "/usr/local/lib/python3.8/site-packages/octue/resources/manifest.py", line 173, in _instantiate_datasets
    self.datasets[key] = Dataset(**dataset, path=path, path_from=self)
  File "/usr/local/lib/python3.8/site-packages/octue/resources/dataset.py", line 47, in __init__
    self.files.add(Datafile.deserialise(file, path_from=self))
  File "/usr/local/lib/python3.8/site-packages/octue/resources/datafile.py", line 185, in deserialise
    datafile = Datafile(**serialised_datafile)
  File "/usr/local/lib/python3.8/site-packages/octue/resources/datafile.py", line 132, in __init__
    self._use_cloud_metadata(**initialisation_parameters)
  File "/usr/local/lib/python3.8/site-packages/octue/resources/datafile.py", line 468, in _use_cloud_metadata
    self.get_cloud_metadata()
  File "/usr/local/lib/python3.8/site-packages/octue/resources/datafile.py", line 229, in get_cloud_metadata
    cloud_metadata = GoogleCloudStorageClient().get_metadata(cloud_path=self.cloud_path)
  File "/usr/local/lib/python3.8/site-packages/octue/cloud/storage/client.py", line 41, in __init__
    self.project_name = credentials.project_id
AttributeError: 'NoneType' object has no attribute 'project_id'"
```
</details>

It seems that **application default credentials** aren't making it into the library. Previously, the CredentialsManager handled that OK because we weren't specifically reading application default credentials - the SDK clients would read them for us. Now, however, we've added code to pull information out [like this](https://github.com/octue/octue-sdk-python/blob/2098548c46907c16fcb55782e64a589152dee652/octue/cloud/storage/client.py#L41) 

### What is the expected behavior?

Should pick up the credentials on the service and therefore be able to ascertain project_id from ADCs

### Proposed solution

- [x] For a quick fix we need to manage application default credentials explicitly [in the get_credentials method](https://github.com/octue/octue-sdk-python/blob/2098548c46907c16fcb55782e64a589152dee652/octue/cloud/credentials.py#L36). [Here is an article](https://medium.com/datamindedbe/application-default-credentials-477879e31cb5) containing some good tips on ADCs

- [x] We recently decided not to inject the credentials as actual JSON anywhere, although we may still be doing this. Add a deprecation warning to [this method](https://github.com/octue/octue-sdk-python/blob/2098548c46907c16fcb55782e64a589152dee652/octue/cloud/credentials.py#L68) to identify where we're using old approaches.

- [x] Once we've updated over any services we find using the JSON-in-envvar method we can remove the handlers for that in a breaking change

- [x] Finally, we can then evaluate whether the credentialsmanager is needed at all, since we'll at that point just be replicating gcloud functionality as far as I can tell.

**Comment by cortadocodes** [comment]
We should also address #354 as part of this.

**Comment by cortadocodes** [comment]
Finished by #380
