### ISSUE TITLE
Error when saving crash diagnostics

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#534]
### What is the current behavior?

When a service crashes, and crash diagnostics are created, you get the following error:
```
TypeError
Object of type TagDict is not JSON serializable
Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/octue/cloud/deployment/google/answer_pub_sub_question.py", line 53, in answer_question service.answer(question, answer_topic=answer_topic) File "/usr/local/lib/python3.9/site-packages/octue/cloud/pub_sub/service.py", line 225, in answer raise error File "/usr/local/lib/python3.9/site-packages/octue/cloud/pub_sub/service.py", line 191, in answer analysis = self.run_function( File "/usr/local/lib/python3.9/site-packages/octue/runner.py", line 224, in run raise crash_diagnostics_save_error File "/usr/local/lib/python3.9/site-packages/octue/runner.py", line 220, in run self._save_crash_diagnostics_data(analysis, sent_messages) File "/usr/local/lib/python3.9/site-packages/octue/runner.py", line 327, in _save_crash_diagnostics_data manifest.to_cloud(storage.path.join(question_diagnostics_path, f"{manifest_type}.json")) File "/usr/local/lib/python3.9/site-packages/octue/resources/manifest.py", line 76, in to_cloud GoogleCloudStorageClient().upload_from_string(string=json.dumps(self.to_primitive()), cloud_path=cloud_path) File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps return _default_encoder.encode(obj) File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode chunks = self.iterencode(o, _one_shot=True) File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode return _iterencode(o, 0) File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default raise TypeError(f'Object of type {o.__class__.__name__} ' TypeError: Object of type TagDict is not JSON serializable
```

### What is the expected behavior?

Crash diagnostics should upload without error.

### Proposed Solution

Looks like we're not using the octue serializer, and this must be the first time using it with a manifest containing tagged files, so would be the first time it's crapped out on us.

**Comment by cortadocodes** [comment]
Oddly I can't reproduce this error with a manifest with a tagged dataset and tagged files. Anyway, the underlying code is fixed to use the encoder now.

**Comment by thclark** [comment]
That is extremely odd, let's hope it fixes the issue
